spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:postgresql://localhost:5432/point_records
    username: postgres
    password: de13050*
  jpa:
    hibernate:
      ddl-auto: update
    database-platform:


